"""empty message

Revision ID: a1e47fb56ddb
Revises: 0e8a70bd8dfd
Create Date: 2024-03-21 14:37:48.368638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1e47fb56ddb'
down_revision = '0e8a70bd8dfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('fileid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(length=20), nullable=False),
    sa.Column('filepath', sa.String(length=50), nullable=False),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('dataid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dataid'], ['dataset.dataid'], ),
    sa.PrimaryKeyConstraint('fileid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file')
    # ### end Alembic commands ###
